name: Sync Metrics and Metric Sources with Statsig

on:
  push:
    paths:
      - 'metrics/*.yml'
      - 'metric_sources/*.yml'

jobs:
  sync_with_statsig:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests PyYAML

      - name: Sync Metrics and Metric Sources
        env:
          STATSIG_API_KEY: ${{ secrets.STATSIG_API_KEY }}
        run: python .github/scripts/statsig_sync.py
